version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/justkyy
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/justkyy/scripts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
    type : 
      - file

hooks:

  BeforeInstall:

  AfterInstall:

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 2500
      runas: ec2-user