version: 0.0
os: linux
files:
  - source: /build/*
    destination: /home/builder/next-app/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/kill_node.sh
      timeout: 300
