import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React, {Suspense} from "react";
import ClientWrapper from "@/components/GeneralWrapper/ClientWrapper";
import NextTopLoader from 'nextjs-toploader';
import ComingSoonUI from "@/components/SSR/ComingSoonUI";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
        >
        <ClientWrapper>
            <NextTopLoader crawl/>
            <Suspense
                fallback={<p>Loading...</p>}>
                {false && <ComingSoonUI/>}
                {true && children}
            </Suspense>
        </ClientWrapper>
        </body>
        </html>
    );
}
